name = "Spring26-Modpack"
author = "cawris"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f61407de9a00aa0422883e1e8b0625a9d444fa9b2c5e194e1b061904e5d3bad"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
