name = "Spring26-Modpack"
author = "cawris"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16d8f00dca7a91e603396801562d1d9c121bcc93dd455e83285b8ee6b0d70522"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
